id: IC3FB34E4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T21:50:55+00:00'
last_modified: '2022-06-09T06:17:30.918393+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15210
  title: འཇིག་རྟེན་སྐྱེ་བོའི་བློ་སྒོ་འབྱེད་པའི་དཔེ་མཚོན་གཏམ་རྒྱུད ༡༠༡།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '5493':
      image_group_id: I1KG15213
      title: Volume 1 of 'jig rten skye bo'i blo sgo 'byed pa'i dpe mtshon gtam rgyud
        101/
      total_pages: 358
      order: 1
      base_file: 5493.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
