id: P007129
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15210
  title: འཇིག་རྟེན་སྐྱེ་བོའི་བློ་སྒོ་འབྱེད་པའི་དཔེ་མཚོན་གཏམ་རྒྱུད ༡༠༡།
  author: ''
  volumes:
    ea625fa2b6a84054a0547e0307399eac:
      image_group_id: I1KG15213
      title: ''
      volume_number: 1
      total_pages: 358
ebook_metadata:
  title: འཇིག་རྟེན་སྐྱེ་བོའི་བློ་སྒོ་འབྱེད་པའི་དཔེ་མཚོན་གཏམ་རྒྱུད ༡༠༡།
  author: ''
  sku: P007129
  cover: cover.jpg
  layers:
  - pagination
