id: P007129
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG15210
  title: འཇིག་རྟེན་སྐྱེ་བོའི་བློ་སྒོ་འབྱེད་པའི་དཔེ་མཚོན་གཏམ་རྒྱུད ༡༠༡།
  author: ''
  volumes:
    d4f605ead1364ef3bc14ee0de5254905:
      image_group_id: I1KG15213
      title: Volume 1 of 'jig rten skye bo'i blo sgo 'byed pa'i dpe mtshon gtam rgyud
        101/
      volume_number: 1
      total_pages: 358
      base_file: v001.txt
